# Generated by Django 4.2.6 on 2023-10-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train_station', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='crew',
            field=models.ManyToManyField(to='train_station.crew'),
        ),
    ]
